-- 55 baseline + 5 refinement/snapshot + 43 Next + 53 Control records.
-- Prints the axiom dependencies of the 55 baseline model-v1 targets, the 35 Mathguard.Next
-- targets (C1/P1/W1), the 8 exported supporting theorems introduced with them, and the G1 Mathguard.Control theorems.
-- Run: lake env lean scripts/Axioms.lean
import Mathguard
open Mathguard
#print axioms applyTransfer_frame
#print axioms applyTransfer_exact
#print axioms applyTransfer_conserves
#print axioms ledger_initial_invariant
#print axioms fresh_commit_preconditions
#print axioms fresh_commit_authorized
#print axioms fresh_commit_versions
#print axioms fresh_commit_caps
#print axioms high_value_exact_approval
#print axioms noncommit_no_mutation
#print axioms duplicate_no_mutation
#print axioms exact_duplicate_replays
#print axioms conflicting_duplicate_blocks
#print axioms ledger_step_invariant
#print axioms ledger_trace_invariant
#print axioms ledger_trace_authorized
#print axioms stale_revision_not_committed
#print axioms reused_high_value_approval_not_committed
#print axioms serial_same_revision_not_both_committed
#print axioms demo_accepts
#print axioms demo_exact_balances
#print axioms demo_blocks_overspend
#print axioms demo_exact_retry
#print axioms demo_high_value_approval_accepts
#print axioms demo_isolated_funds_rejection
#print axioms budget_initial_invariant
#print axioms reserve_preserves
#print axioms reserve_exact
#print axioms reserve_over_limit
#print axioms reserve_same_id_rejected
#print axioms settle_preserves
#print axioms settle_exact
#print axioms settled_ticket_cannot_settle_twice
#print axioms charge_bound_preserves
#print axioms reconfigure_preserves
#print axioms budget_step_preserves
#print axioms budget_trace_preserves
#print axioms demo_budget_first_reservation
#print axioms demo_budget_second_reservation_denied
#print axioms label_join_upper_left
#print axioms label_join_upper_right
#print axioms label_join_least
#print axioms label_join_associative
#print axioms label_trace_never_lowers
#print axioms label_trace_contains_observation
#print axioms output_clearance_enforced
#print axioms public_sink_rejects_sensitive
#print axioms trust_gate_enforced
#print axioms semantic_cannot_override_hard
#print axioms semantic_veto
#print axioms final_effects_subset_hard
#print axioms semantic_tightening_never_adds_effect
#print axioms demo_secret_export_denied
#print axioms demo_internal_export_allowed
#print axioms demo_public_export_allowed
-- C1 composite financial admission (14)
#print axioms Mathguard.Next.composite_initial_invariant
#print axioms Mathguard.Next.composite_commit_exact
#print axioms Mathguard.Next.composite_commit_gates
#print axioms Mathguard.Next.composite_step_invariant
#print axioms Mathguard.Next.composite_label_never_lowers
#print axioms Mathguard.Next.composite_observation_retained
#print axioms Mathguard.Next.composite_noncommit_financial_nonmutation
#print axioms Mathguard.Next.composite_hard_deny_cannot_be_overridden
#print axioms Mathguard.Next.composite_sensitive_flow_denied
#print axioms Mathguard.Next.composite_budget_denial_prevents_commit
#print axioms Mathguard.Next.composite_replay_no_new_reservation
#print axioms Mathguard.Next.composite_trace_invariant
#print axioms Mathguard.Next.composite_trace_label_never_lowers
#print axioms Mathguard.Next.demo_composite_accepts
-- P1 policy activation and historical evidence (12)
#print axioms Mathguard.Next.governed_initial_invariant
#print axioms Mathguard.Next.governed_step_invariant
#print axioms Mathguard.Next.governed_trace_invariant
#print axioms Mathguard.Next.policy_reload_preserves_financial_state
#print axioms Mathguard.Next.nonincreasing_policy_epoch_rejected
#print axioms Mathguard.Next.policy_epoch_never_decreases
#print axioms Mathguard.Next.policy_epoch_trace_monotone
#print axioms Mathguard.Next.old_epoch_cannot_fresh_commit_after_reload
#print axioms Mathguard.Next.governed_history_extends
#print axioms Mathguard.Next.historical_authorization_uses_own_snapshot
#print axioms Mathguard.Next.demo_reload_blocks_old_request
#print axioms Mathguard.Next.demo_reload_accepts_new_request
-- W1 typed wire projection (9)
#print axioms Mathguard.Next.wire_roundtrip
#print axioms Mathguard.Next.wire_decode_preserves_fields
#print axioms Mathguard.Next.wire_projection_injective
#print axioms Mathguard.Next.wire_source_out_of_range
#print axioms Mathguard.Next.wire_destination_out_of_range
#print axioms Mathguard.Next.wire_valid_indices_decode
#print axioms Mathguard.Next.wire_approval_cannot_match_changed_fields
#print axioms Mathguard.Next.demo_wire_decodes
#print axioms Mathguard.Next.demo_wire_rejects_unknown_account
-- Mathguard.Next supporting theorems (8)
#print axioms Mathguard.Next.compositeStep_label
#print axioms Mathguard.Next.compositeStep_of_commit
#print axioms Mathguard.Next.compositeStep_committed_iff
#print axioms Mathguard.Next.compositeStep_noncommit
#print axioms Mathguard.Next.transferGate_eq_true_iff
#print axioms Mathguard.Next.EvidenceChain.snoc
#print axioms Mathguard.Next.evidenceSound_of_step
#print axioms Mathguard.Next.evidenceAuthorized_of_sound
-- G1 generic control-layer decision kernel (Mathguard.Control)
#print axioms Mathguard.Control.Decision.executes_eq_true_iff
#print axioms Mathguard.Control.Decision.combine_executes
#print axioms Mathguard.Control.Decision.AtMost.refl
#print axioms Mathguard.Control.Decision.AtMost.trans
#print axioms Mathguard.Control.Decision.AtMost.combine
#print axioms Mathguard.Control.Decision.AtMost.combine_left
#print axioms Mathguard.Control.Decision.AtMost.combine_right
#print axioms Mathguard.Control.Decision.AtMost.when
#print axioms Mathguard.Control.Decision.AtMost.executes
#print axioms Mathguard.Control.hard_atMost_gate
#print axioms Mathguard.Control.semantic_atMost_gate
#print axioms Mathguard.Control.gate_executes_imp_hard
#print axioms Mathguard.Control.gate_executes_imp_semantic
#print axioms Mathguard.Control.strict_timeout_denies
#print axioms Mathguard.Control.strict_malformed_denies
#print axioms Mathguard.Control.balanced_timeout_not_executed
#print axioms Mathguard.Control.permissive_timeout_alerts
#print axioms Mathguard.Control.hardDecision_deny
#print axioms Mathguard.Control.unauthenticated_denied
#print axioms Mathguard.Control.signature_denied
#print axioms Mathguard.Control.model_not_allowed_denied
#print axioms Mathguard.Control.tool_not_allowed_denied
#print axioms Mathguard.Control.irreversible_requires_approval
#print axioms Mathguard.Control.artifact_admitted_pinned_safe
#print axioms Mathguard.Control.pii_block_denied
#print axioms Mathguard.Control.pii_redact_flagged
#print axioms Mathguard.Control.signatureHit_mono
#print axioms Mathguard.Control.kindDecision_mono
#print axioms Mathguard.Control.piiDecision_mono
#print axioms Mathguard.Control.hardDecision_mono
#print axioms Mathguard.Control.fallbackDecision_mono
#print axioms Mathguard.Control.semanticDecision_mono
#print axioms Mathguard.Control.gate_mono
#print axioms Mathguard.Control.gate_mono_executes
#print axioms Mathguard.Control.reload_invalid_keeps
#print axioms Mathguard.Control.reload_valid_activates
#print axioms Mathguard.Control.reload_epoch_mono
#print axioms Mathguard.Control.reloadAll_preserves_valid
#print axioms Mathguard.Control.reloadAll_active_valid
#print axioms Mathguard.Control.no_policy_fail_closed
#print axioms Mathguard.Control.sessionStep_steps_le
#print axioms Mathguard.Control.sessionRun_steps_le
#print axioms Mathguard.Control.sessionStep_log
#print axioms Mathguard.Control.sessionRun_log
#print axioms Mathguard.Control.blockedCount_step
#print axioms Mathguard.Control.recall_owned
#print axioms Mathguard.Control.demo_control_policy_valid
#print axioms Mathguard.Control.demo_benign_prompt_executes
#print axioms Mathguard.Control.demo_feed_signature_blocks
#print axioms Mathguard.Control.demo_pii_redacted_not_blocked
#print axioms Mathguard.Control.demo_pickle_artifact_blocked
#print axioms Mathguard.Control.demo_transfer_waits_for_approval
#print axioms Mathguard.Control.demo_invalid_reload_keeps_last_good

-- Existing performance refinements preserved.
#print axioms reservedTotals_eq
#print axioms reservedAt_eq
#print axioms reserveOptimized_eq
#print axioms budgetStepOptimized_eq
#print axioms ledgerResultUpdate_eq
