-- Prints 55 model-v1 targets plus 5 refinement/snapshot bridge targets.
-- Run: lake env lean scripts/Axioms.lean
import Mathguard
open Mathguard
#print axioms applyTransfer_frame
#print axioms applyTransfer_exact
#print axioms applyTransfer_conserves
#print axioms ledger_initial_invariant
#print axioms fresh_commit_preconditions
#print axioms fresh_commit_authorized
#print axioms fresh_commit_versions
#print axioms fresh_commit_caps
#print axioms high_value_exact_approval
#print axioms noncommit_no_mutation
#print axioms duplicate_no_mutation
#print axioms exact_duplicate_replays
#print axioms conflicting_duplicate_blocks
#print axioms ledger_step_invariant
#print axioms ledger_trace_invariant
#print axioms ledger_trace_authorized
#print axioms stale_revision_not_committed
#print axioms reused_high_value_approval_not_committed
#print axioms serial_same_revision_not_both_committed
#print axioms demo_accepts
#print axioms demo_exact_balances
#print axioms demo_blocks_overspend
#print axioms demo_exact_retry
#print axioms demo_high_value_approval_accepts
#print axioms demo_isolated_funds_rejection
#print axioms budget_initial_invariant
#print axioms reserve_preserves
#print axioms reserve_exact
#print axioms reserve_over_limit
#print axioms reserve_same_id_rejected
#print axioms settle_preserves
#print axioms settle_exact
#print axioms settled_ticket_cannot_settle_twice
#print axioms charge_bound_preserves
#print axioms reconfigure_preserves
#print axioms budget_step_preserves
#print axioms budget_trace_preserves
#print axioms demo_budget_first_reservation
#print axioms demo_budget_second_reservation_denied
#print axioms label_join_upper_left
#print axioms label_join_upper_right
#print axioms label_join_least
#print axioms label_join_associative
#print axioms label_trace_never_lowers
#print axioms label_trace_contains_observation
#print axioms output_clearance_enforced
#print axioms public_sink_rejects_sensitive
#print axioms trust_gate_enforced
#print axioms semantic_cannot_override_hard
#print axioms semantic_veto
#print axioms final_effects_subset_hard
#print axioms semantic_tightening_never_adds_effect
#print axioms demo_secret_export_denied
#print axioms demo_internal_export_allowed
#print axioms demo_public_export_allowed
-- Additional refinement/snapshot bridge targets, separate from the baseline 55.
#print axioms reservedTotals_eq
#print axioms reservedAt_eq
#print axioms reserveOptimized_eq
#print axioms budgetStepOptimized_eq
#print axioms ledgerResultUpdate_eq
